name: 'Configure Laravel Nova'
description: 'A GitHub action for configuring composer to use Laravel Nova.'

branding:
  icon: git-branch
  color: yellow

inputs:
  user:
    description: 'Nova user'
    required: true
    default: undefined
  token:
    description: 'Nova access token'
    required: true
    default: undefined
runs:
  using: 'composite'
  steps:
    - name: Configure composer
      shell: bash
      run: |
        composer config -g 'http-basic.nova.laravel.com' '${{ inputs.user }}' '${{ inputs.token }}'
        composer config -g repo.nova composer 'https://nova.laravel.com'
